language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -d -k "$SECRET_FILES_KEY" -in release.jks.enc -out release.jks
script:
  - ./gradlew clean build assembleRelease -Pversion_code=$TRAVIS_BUILD_NUMBER -Pversion_name=0.1.0.$TRAVIS_BUILD_NUMBER -Pandroid.signingConfigs.release.storePassword=$KEYSTORE_PASSWORD -Pandroid.signingConfigs.release.keyAlias=$KEY_ALIAS -Pandroid.signingConfigs.release.keyPassword=$KEY_PASSWORD
after_success:
